spring:
  data:
    mongodb:
      database: java_pro
      uri: mongodb://localhost:27017
  application:
            name: JavaPro
    devtools:
       restart:
           enabled: true
       livereload:
           enabled: true

